#!/usr/bin/python3

#usage : passmanage entity
# entity is like 'alwaysdata', 'sncf'
# if entity is not found, partially, then we ask for a new account definition
# if multiples matchs, we display 'did u mean ' + matches

# for a new account, we ask :
# entity (example : website name)
# user (example : email)
# enter password (empty autogenerated)
# if empty we generate a password, and we display it

# if often used, it's a mix of known stuff

# if no .config/passmanage.conf, we generate it, with a filename like ~/.passmanage.db

# now, how to i edit an encrypted file ?

# and how do i convert an array, well a thing, into maybe json
